---
title: Git To Book
author: Dennis Iversen
rights: Creative Commons Non-Commercial Share Alike 3.0
language: en-US
cover-image: images/cover.png

# pandoc format arguments
format-arguments:
    pdf: -s -S   --latex-engine pdflatex --template=templates/default.latex --number-sections -V documentclass=memoir -V geometry:margin=1in -V lang=danish --toc --chapters
    html: -s -S --chapters --template=templates/bootstrap.html --css=css/bootstrap.css --number-sections --toc -t html5
    epub: -s -S  --epub-chapter-level=3 --number-sections --toc --epub-chapter-level=4 
...
