---
title: Git To Book
subject: Gittobook documentation
author: Dennis Iversen
keywords: ebooks, pandoc, pdf, html
rights: Creative Commons Non-Commercial Share Alike 3.0
language: en-US
cover-image: images/cover.png

# pandoc format arguments
# because of security these options are not parsed in the online version
# other useful options could be: 
# pdf: --chapters -V geometry:margin=1in -V documentclass=memoir -V lang=danish
format-arguments:
    pdf: -s -S --latex-engine=pdflatex --template=templates/default.latex --number-sections --toc
    html: -s -S --chapters --template=templates/bootstrap.html --css=css/bootstrap.css --number-sections --toc -t html5
    epub: -s -S  --epub-chapter-level=3 --number-sections --toc --epub-chapter-level=4 
# ignore the following files
# ignore-files: 
#    - README.md

# 
# docs-folder: docs/
...
