---
title: Git To Book Documentation
Subtitle: A simple way to generate PDF, EPUB, MOBI, HTML, etc from Markdown and Pandoc
subject: Gittobook documentation
test: test
author:
- Dennis Iversen
- Another author
keywords: ebooks, pandoc, pdf, html
rights: Creative Commons Non-Commercial Share Alike 3.0
language: en-US
#cover-image: "images/cover.png"
lang: en
# Note you will need quotes around dates
date: '2015-01-27'

# pandoc format arguments
# because of security these options are not parsed in the online version
# other useful options could be: 
# --from markdown_strict 
# pdf: --chapters -V geometry:margin=1in -V documentclass=memoir -V lang=danish
format-arguments:
    #pdf: --number-sections -V mainfont='TeX Gyre Bonum' -V sansfont='Times New Roman' -V monofont=Arial -V fontsize=12pt -V version=1.10 --toc
    pdf: -V mainfont='Latin Modern Roman' -V sansfont='Times New Roman' -V monofont=Arial -V fontsize=12pt -V version=1.10 --toc
    #html: -S --css=css/default.css --template=templates/default.html --toc-depth=3 --chapters --number-sections --toc
    html: -S --template=templates/body.html --toc-depth=3 --chapters --number-sections --toc
    #html: -s -S --css=css/bootstrap.css --template=templates/bootstrap.html --toc-depth=3 --chapters --number-sections --toc -t html5
    epub: -S --epub-chapter-level=3 --number-sections --toc --epub-chapter-level=4
    #texi: -s 
    mobi: ok
# xml docbook
    docbook: -s -S 
# chunked xhtml (--skip validation(
# xmlto xhtml -m templates/docbook.xsl --skip git-to-book-docs.db -o test/
# ignore the following files
#ignore-files: 
#    - README.md

# 
# docs-folder: docs/
# fonts: Comic Sans MS
...
